name: app2
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.1
  retrofit: ^3.3.1
  json_annotation: ^4.8.0
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^4.2.0
  json_serializable: ^6.6.0
  flutter_lints: ^2.0.0

  build_runner: ^2.3.3

flutter:
  uses-material-design: true

